### ISSUE TITLE
data loss after OS reinstall

### ISSUE THREAD

**Issue by timabell** [notriddle/budget-envelopes#33]
Great app, many thanks for it.

I've reinstalled my OS (cyanogenmod) and the app (via f-droid), keeping my home dir / sdcard intact, but all the data is gone.

Where does it actually keep the data?

Thanks

**Comment by notriddle** [comment]
It keeps the data in the app data area (Titanium Backup would have saved
it), though you can back up to SD Card if you want. I don't store on SD by
default because I don't want your private financial data available to every
random app you install.

**Comment by timabell** [comment]
Thanks, clearly I still have a lot more to learn about android. I hadn't heard of this folder and naively assumed everything would be in home like on my linux desktops. Sigh.

http://android.stackexchange.com/questions/47924/where-android-apps-store-data
